name: Preprocessing Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn

    - name: Run preprocessing script
      run: |
        python preprocessing/automate_Nama-siswa.py

    - name: Commit and push preprocessed dataset
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add preprocessing/namadataset_preprocessing/
        git commit -m "Update preprocessed dataset via workflow" || echo "No changes to commit"
        git push
